export const height = 750
export const gridSize = 10
export const fps = 60
export const delayEnd = 2
export const width = height * 0.9
export const cell = width / (gridSize + 2)
export const stroke = cell / 12
export const dot = stroke
export const margin = height - (gridSize + 1) * cell
export const colourBoard = '#ff4500'
export const colourBorder = '#fffaf0'
export const colourDot = '#fffaf0'
export const colourAi = '#0000ff';
export const colourAiLight = 'rgba(0, 0, 255, 0.3)'
export const colourPlayer = '#ff0000'
export const colourPlayerLight = 'rgba(255, 0, 0, 0.3)'
export const tie ='#111111'
